-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "TxType" ADD VALUE 'CAPITAL_WITHDRAWAL';
ALTER TYPE "TxType" ADD VALUE 'INVESTMENT_RETURN';
ALTER TYPE "TxType" ADD VALUE 'PROJECT_REVENUE';
ALTER TYPE "TxType" ADD VALUE 'INTEREST_INCOME';
ALTER TYPE "TxType" ADD VALUE 'DIVIDEND_INCOME';
ALTER TYPE "TxType" ADD VALUE 'OTHER_INCOME';
ALTER TYPE "TxType" ADD VALUE 'PROJECT_DISBURSEMENT';
ALTER TYPE "TxType" ADD VALUE 'ASSET_PURCHASE';
ALTER TYPE "TxType" ADD VALUE 'LOAN_REPAYMENT_RECEIVED';
ALTER TYPE "TxType" ADD VALUE 'TRANSPORT_TRAVEL';
ALTER TYPE "TxType" ADD VALUE 'COMMUNICATION_INTERNET';
ALTER TYPE "TxType" ADD VALUE 'OFFICE_ADMINISTRATION';
ALTER TYPE "TxType" ADD VALUE 'PRINTING_STATIONERY';
ALTER TYPE "TxType" ADD VALUE 'SALARIES_WAGES';
ALTER TYPE "TxType" ADD VALUE 'UTILITIES';
ALTER TYPE "TxType" ADD VALUE 'INSURANCE';
ALTER TYPE "TxType" ADD VALUE 'MEALS_ENTERTAINMENT';
ALTER TYPE "TxType" ADD VALUE 'DIRECTOR_LOAN_TO_COMPANY';
ALTER TYPE "TxType" ADD VALUE 'DIRECTOR_LOAN_REPAYMENT';
ALTER TYPE "TxType" ADD VALUE 'LOAN_REPAYMENT_EXTERNAL';
ALTER TYPE "TxType" ADD VALUE 'WITHHOLDING_TAX';
ALTER TYPE "TxType" ADD VALUE 'VAT_PAYABLE';
ALTER TYPE "TxType" ADD VALUE 'CORPORATE_TAX_PROVISION';
ALTER TYPE "TxType" ADD VALUE 'FOREIGN_EXCHANGE_GAIN';
ALTER TYPE "TxType" ADD VALUE 'FOREIGN_EXCHANGE_LOSS';
